version: '3.7'
services:
  solr:
    image: solr:9.4.0
    container_name: solr
    ports:
      - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181
    volumes:
      - './solr:/var/solr'
    networks:
      - solr
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper:3.7.2
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr
networks:
  solr: